kind: Pod
apiVersion: v1
metadata:
  name: db-pg-baseline
  labels:
    app: db-pg-baseline
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  restartPolicy: Never
  containers:
  - name: db-pg-baseline
    image: achuala.in/ledger-pg-migration:v1
    envFrom:
    - secretRef:
        name: ledger-postgres-flyway
    command: ["flyway", "baseline", "-baselineVersion=0"]