application:
  name: ledger
port: 10001
profile: debug #release|debug
version: 0.1
nats:
  hosts: "nats://nats:nats@localhost:4222"
db:
  uri: "postgresql://postgres:postgres@localhost:5432/ledger?sslmode=disable"
  driver: "postgres"