// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: account.proto

package glaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralLedgerAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId           string `protobuf:"bytes,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	OrganizationId     string `protobuf:"bytes,3,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
	Name               string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Glcode             string `protobuf:"bytes,5,opt,name=glcode,proto3" json:"glcode,omitempty"`
	Type               string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Description        string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Disabled           bool   `protobuf:"varint,8,opt,name=disabled,proto3" json:"disabled,omitempty"`
	AllowManualEntries bool   `protobuf:"varint,9,opt,name=allowManualEntries,proto3" json:"allowManualEntries,omitempty"`
	Usage              string `protobuf:"bytes,10,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *GeneralLedgerAccount) Reset() {
	*x = GeneralLedgerAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralLedgerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralLedgerAccount) ProtoMessage() {}

func (x *GeneralLedgerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralLedgerAccount.ProtoReflect.Descriptor instead.
func (*GeneralLedgerAccount) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralLedgerAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneralLedgerAccount) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GeneralLedgerAccount) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GeneralLedgerAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneralLedgerAccount) GetGlcode() string {
	if x != nil {
		return x.Glcode
	}
	return ""
}

func (x *GeneralLedgerAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneralLedgerAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GeneralLedgerAccount) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *GeneralLedgerAccount) GetAllowManualEntries() bool {
	if x != nil {
		return x.AllowManualEntries
	}
	return false
}

func (x *GeneralLedgerAccount) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type GetGLAByIdRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGLAByIdRq) Reset() {
	*x = GetGLAByIdRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGLAByIdRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGLAByIdRq) ProtoMessage() {}

func (x *GetGLAByIdRq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGLAByIdRq.ProtoReflect.Descriptor instead.
func (*GetGLAByIdRq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetGLAByIdRq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGLAByIdRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Glaccount *GeneralLedgerAccount `protobuf:"bytes,2,opt,name=glaccount,proto3" json:"glaccount,omitempty"`
}

func (x *GetGLAByIdRs) Reset() {
	*x = GetGLAByIdRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGLAByIdRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGLAByIdRs) ProtoMessage() {}

func (x *GetGLAByIdRs) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGLAByIdRs.ProtoReflect.Descriptor instead.
func (*GetGLAByIdRs) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetGLAByIdRs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGLAByIdRs) GetGlaccount() *GeneralLedgerAccount {
	if x != nil {
		return x.Glaccount
	}
	return nil
}

// request parameters for method get_accounts_by_organization
type GetGLAcctsByOrgRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// organization unique identifier
	OrganizationId string `protobuf:"bytes,1,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
}

func (x *GetGLAcctsByOrgRq) Reset() {
	*x = GetGLAcctsByOrgRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGLAcctsByOrgRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGLAcctsByOrgRq) ProtoMessage() {}

func (x *GetGLAcctsByOrgRq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGLAcctsByOrgRq.ProtoReflect.Descriptor instead.
func (*GetGLAcctsByOrgRq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetGLAcctsByOrgRq) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// response parameters for method get_accounts_by_organization
type GetGLAcctsByOrgRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GlAccounts []*GeneralLedgerAccount `protobuf:"bytes,2,rep,name=glAccounts,proto3" json:"glAccounts,omitempty"`
}

func (x *GetGLAcctsByOrgRs) Reset() {
	*x = GetGLAcctsByOrgRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGLAcctsByOrgRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGLAcctsByOrgRs) ProtoMessage() {}

func (x *GetGLAcctsByOrgRs) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGLAcctsByOrgRs.ProtoReflect.Descriptor instead.
func (*GetGLAcctsByOrgRs) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetGLAcctsByOrgRs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGLAcctsByOrgRs) GetGlAccounts() []*GeneralLedgerAccount {
	if x != nil {
		return x.GlAccounts
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

var file_account_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xae, 0x02, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x6c, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x6c, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6e,
	0x75, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x4c, 0x41, 0x42, 0x79, 0x49, 0x64, 0x52, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x5b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x4c, 0x41, 0x42, 0x79, 0x49, 0x64, 0x52, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x67, 0x6c, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x09, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x73, 0x42, 0x79, 0x4f, 0x72, 0x67,
	0x52, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x73, 0x42, 0x79, 0x4f, 0x72, 0x67, 0x52, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x67, 0x6c, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x0a, 0x67, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x27,
	0x5a, 0x25, 0x61, 0x63, 0x68, 0x75, 0x61, 0x6c, 0x61, 0x2e, 0x69, 0x6e, 0x2f, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x72, 0x2f, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x67, 0x6c,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData = file_account_proto_rawDesc
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_proto_rawDescData)
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_account_proto_goTypes = []interface{}{
	(*GeneralLedgerAccount)(nil), // 0: GeneralLedgerAccount
	(*GetGLAByIdRq)(nil),         // 1: GetGLAByIdRq
	(*GetGLAByIdRs)(nil),         // 2: GetGLAByIdRs
	(*GetGLAcctsByOrgRq)(nil),    // 3: GetGLAcctsByOrgRq
	(*GetGLAcctsByOrgRs)(nil),    // 4: GetGLAcctsByOrgRs
}
var file_account_proto_depIdxs = []int32{
	0, // 0: GetGLAByIdRs.glaccount:type_name -> GeneralLedgerAccount
	0, // 1: GetGLAcctsByOrgRs.glAccounts:type_name -> GeneralLedgerAccount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralLedgerAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGLAByIdRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGLAByIdRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGLAcctsByOrgRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGLAcctsByOrgRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_rawDesc = nil
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
