// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: gl_account.proto

package glaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralLedgerAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId           string `protobuf:"bytes,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Name               string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Glcode             string `protobuf:"bytes,4,opt,name=glcode,proto3" json:"glcode,omitempty"`
	Type               string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Description        string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Disabled           bool   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	AllowManualEntries bool   `protobuf:"varint,8,opt,name=allowManualEntries,proto3" json:"allowManualEntries,omitempty"`
	Usage              string `protobuf:"bytes,9,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *GeneralLedgerAccount) Reset() {
	*x = GeneralLedgerAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralLedgerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralLedgerAccount) ProtoMessage() {}

func (x *GeneralLedgerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralLedgerAccount.ProtoReflect.Descriptor instead.
func (*GeneralLedgerAccount) Descriptor() ([]byte, []int) {
	return file_gl_account_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralLedgerAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneralLedgerAccount) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GeneralLedgerAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeneralLedgerAccount) GetGlcode() string {
	if x != nil {
		return x.Glcode
	}
	return ""
}

func (x *GeneralLedgerAccount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneralLedgerAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GeneralLedgerAccount) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *GeneralLedgerAccount) GetAllowManualEntries() bool {
	if x != nil {
		return x.AllowManualEntries
	}
	return false
}

func (x *GeneralLedgerAccount) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

type FindGLAByIdRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindGLAByIdRq) Reset() {
	*x = FindGLAByIdRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindGLAByIdRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGLAByIdRq) ProtoMessage() {}

func (x *FindGLAByIdRq) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGLAByIdRq.ProtoReflect.Descriptor instead.
func (*FindGLAByIdRq) Descriptor() ([]byte, []int) {
	return file_gl_account_proto_rawDescGZIP(), []int{1}
}

func (x *FindGLAByIdRq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindGLAByIdRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Glaccount *GeneralLedgerAccount `protobuf:"bytes,2,opt,name=glaccount,proto3" json:"glaccount,omitempty"`
}

func (x *FindGLAByIdRs) Reset() {
	*x = FindGLAByIdRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindGLAByIdRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGLAByIdRs) ProtoMessage() {}

func (x *FindGLAByIdRs) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGLAByIdRs.ProtoReflect.Descriptor instead.
func (*FindGLAByIdRs) Descriptor() ([]byte, []int) {
	return file_gl_account_proto_rawDescGZIP(), []int{2}
}

func (x *FindGLAByIdRs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindGLAByIdRs) GetGlaccount() *GeneralLedgerAccount {
	if x != nil {
		return x.Glaccount
	}
	return nil
}

var File_gl_account_proto protoreflect.FileDescriptor

var file_gl_account_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x86, 0x02, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x4c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x6c, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x6c, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x61,
	0x6e, 0x75, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x46,
	0x69, 0x6e, 0x64, 0x47, 0x4c, 0x41, 0x42, 0x79, 0x49, 0x64, 0x52, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5c, 0x0a, 0x0d,
	0x46, 0x69, 0x6e, 0x64, 0x47, 0x4c, 0x41, 0x42, 0x79, 0x49, 0x64, 0x52, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x09, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x61, 0x63,
	0x68, 0x75, 0x61, 0x6c, 0x61, 0x2e, 0x69, 0x6e, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f,
	0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gl_account_proto_rawDescOnce sync.Once
	file_gl_account_proto_rawDescData = file_gl_account_proto_rawDesc
)

func file_gl_account_proto_rawDescGZIP() []byte {
	file_gl_account_proto_rawDescOnce.Do(func() {
		file_gl_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_gl_account_proto_rawDescData)
	})
	return file_gl_account_proto_rawDescData
}

var file_gl_account_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gl_account_proto_goTypes = []interface{}{
	(*GeneralLedgerAccount)(nil), // 0: GeneralLedgerAccount
	(*FindGLAByIdRq)(nil),        // 1: FindGLAByIdRq
	(*FindGLAByIdRs)(nil),        // 2: FindGLAByIdRs
}
var file_gl_account_proto_depIdxs = []int32{
	0, // 0: FindGLAByIdRs.glaccount:type_name -> GeneralLedgerAccount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gl_account_proto_init() }
func file_gl_account_proto_init() {
	if File_gl_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gl_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralLedgerAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindGLAByIdRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindGLAByIdRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gl_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gl_account_proto_goTypes,
		DependencyIndexes: file_gl_account_proto_depIdxs,
		MessageInfos:      file_gl_account_proto_msgTypes,
	}.Build()
	File_gl_account_proto = out.File
	file_gl_account_proto_rawDesc = nil
	file_gl_account_proto_goTypes = nil
	file_gl_account_proto_depIdxs = nil
}
