// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: gl_account_journal.proto

package glaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewGLAcctJournalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId  string                          `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	ExternalRef    string                          `protobuf:"bytes,2,opt,name=externalRef,proto3" json:"externalRef,omitempty"`
	EntryDate      string                          `protobuf:"bytes,3,opt,name=entryDate,proto3" json:"entryDate,omitempty"`
	DebitInfo      *NewGLAcctJournalEntry_AcctInfo `protobuf:"bytes,4,opt,name=debitInfo,proto3" json:"debitInfo,omitempty"`
	CreditInfo     *NewGLAcctJournalEntry_AcctInfo `protobuf:"bytes,5,opt,name=creditInfo,proto3" json:"creditInfo,omitempty"`
	AdditionalInfo map[string]string               `protobuf:"bytes,6,rep,name=additionalInfo,proto3" json:"additionalInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NewGLAcctJournalEntry) Reset() {
	*x = NewGLAcctJournalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGLAcctJournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGLAcctJournalEntry) ProtoMessage() {}

func (x *NewGLAcctJournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGLAcctJournalEntry.ProtoReflect.Descriptor instead.
func (*NewGLAcctJournalEntry) Descriptor() ([]byte, []int) {
	return file_gl_account_journal_proto_rawDescGZIP(), []int{0}
}

func (x *NewGLAcctJournalEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *NewGLAcctJournalEntry) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *NewGLAcctJournalEntry) GetEntryDate() string {
	if x != nil {
		return x.EntryDate
	}
	return ""
}

func (x *NewGLAcctJournalEntry) GetDebitInfo() *NewGLAcctJournalEntry_AcctInfo {
	if x != nil {
		return x.DebitInfo
	}
	return nil
}

func (x *NewGLAcctJournalEntry) GetCreditInfo() *NewGLAcctJournalEntry_AcctInfo {
	if x != nil {
		return x.CreditInfo
	}
	return nil
}

func (x *NewGLAcctJournalEntry) GetAdditionalInfo() map[string]string {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

type PostNewGLAcctJrnlEntryRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *NewGLAcctJournalEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Meta  map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PostNewGLAcctJrnlEntryRq) Reset() {
	*x = PostNewGLAcctJrnlEntryRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostNewGLAcctJrnlEntryRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewGLAcctJrnlEntryRq) ProtoMessage() {}

func (x *PostNewGLAcctJrnlEntryRq) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewGLAcctJrnlEntryRq.ProtoReflect.Descriptor instead.
func (*PostNewGLAcctJrnlEntryRq) Descriptor() ([]byte, []int) {
	return file_gl_account_journal_proto_rawDescGZIP(), []int{1}
}

func (x *PostNewGLAcctJrnlEntryRq) GetEntry() *NewGLAcctJournalEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *PostNewGLAcctJrnlEntryRq) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PostNewGLAcctJrnlEntryRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PostNewGLAcctJrnlEntryRs) Reset() {
	*x = PostNewGLAcctJrnlEntryRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_journal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostNewGLAcctJrnlEntryRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewGLAcctJrnlEntryRs) ProtoMessage() {}

func (x *PostNewGLAcctJrnlEntryRs) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_journal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewGLAcctJrnlEntryRs.ProtoReflect.Descriptor instead.
func (*PostNewGLAcctJrnlEntryRs) Descriptor() ([]byte, []int) {
	return file_gl_account_journal_proto_rawDescGZIP(), []int{2}
}

func (x *PostNewGLAcctJrnlEntryRs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PostNewGLAcctJrnlEntryRs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GLAccountEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalRef string `protobuf:"bytes,2,opt,name=externalRef,proto3" json:"externalRef,omitempty"`
	ReversalId  string `protobuf:"bytes,3,opt,name=reversalId,proto3" json:"reversalId,omitempty"`
	EntryDate   string `protobuf:"bytes,4,opt,name=entryDate,proto3" json:"entryDate,omitempty"`
	GlAccountId string `protobuf:"bytes,5,opt,name=gl_account_id,json=glAccountId,proto3" json:"gl_account_id,omitempty"`
}

func (x *GLAccountEntry) Reset() {
	*x = GLAccountEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_journal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GLAccountEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GLAccountEntry) ProtoMessage() {}

func (x *GLAccountEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_journal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GLAccountEntry.ProtoReflect.Descriptor instead.
func (*GLAccountEntry) Descriptor() ([]byte, []int) {
	return file_gl_account_journal_proto_rawDescGZIP(), []int{3}
}

func (x *GLAccountEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GLAccountEntry) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *GLAccountEntry) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

func (x *GLAccountEntry) GetEntryDate() string {
	if x != nil {
		return x.EntryDate
	}
	return ""
}

func (x *GLAccountEntry) GetGlAccountId() string {
	if x != nil {
		return x.GlAccountId
	}
	return ""
}

type NewGLAcctJournalEntry_AcctInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlAccountId string  `protobuf:"bytes,1,opt,name=gl_account_id,json=glAccountId,proto3" json:"gl_account_id,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount      float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *NewGLAcctJournalEntry_AcctInfo) Reset() {
	*x = NewGLAcctJournalEntry_AcctInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_account_journal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGLAcctJournalEntry_AcctInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGLAcctJournalEntry_AcctInfo) ProtoMessage() {}

func (x *NewGLAcctJournalEntry_AcctInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gl_account_journal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGLAcctJournalEntry_AcctInfo.ProtoReflect.Descriptor instead.
func (*NewGLAcctJournalEntry_AcctInfo) Descriptor() ([]byte, []int) {
	return file_gl_account_journal_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NewGLAcctJournalEntry_AcctInfo) GetGlAccountId() string {
	if x != nil {
		return x.GlAccountId
	}
	return ""
}

func (x *NewGLAcctJournalEntry_AcctInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NewGLAcctJournalEntry_AcctInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_gl_account_journal_proto protoreflect.FileDescriptor

var file_gl_account_journal_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6a, 0x6f, 0x75,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfe, 0x03, 0x0a, 0x15, 0x4e,
	0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x64, 0x65,
	0x62, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09,
	0x64, 0x65, 0x62, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3f, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x52, 0x0a, 0x0e, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x6f,
	0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e,
	0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x68,
	0x0a, 0x08, 0x41, 0x63, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0d, 0x67, 0x6c,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x67, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x41, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xba, 0x01, 0x0a, 0x18,
	0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x72, 0x6e,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x71, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41,
	0x63, 0x63, 0x74, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x37, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x47, 0x4c,
	0x41, 0x63, 0x63, 0x74, 0x4a, 0x72, 0x6e, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x71, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a,
	0x37, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x42, 0x0a, 0x18, 0x50, 0x6f, 0x73, 0x74,
	0x4e, 0x65, 0x77, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x74, 0x4a, 0x72, 0x6e, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa4, 0x01, 0x0a,
	0x0e, 0x47, 0x4c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x22, 0x0a, 0x0d, 0x67, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x42, 0x27, 0x5a, 0x25, 0x61, 0x63, 0x68, 0x75, 0x61, 0x6c, 0x61, 0x2e, 0x69,
	0x6e, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x3b, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gl_account_journal_proto_rawDescOnce sync.Once
	file_gl_account_journal_proto_rawDescData = file_gl_account_journal_proto_rawDesc
)

func file_gl_account_journal_proto_rawDescGZIP() []byte {
	file_gl_account_journal_proto_rawDescOnce.Do(func() {
		file_gl_account_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_gl_account_journal_proto_rawDescData)
	})
	return file_gl_account_journal_proto_rawDescData
}

var file_gl_account_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gl_account_journal_proto_goTypes = []interface{}{
	(*NewGLAcctJournalEntry)(nil),          // 0: NewGLAcctJournalEntry
	(*PostNewGLAcctJrnlEntryRq)(nil),       // 1: PostNewGLAcctJrnlEntryRq
	(*PostNewGLAcctJrnlEntryRs)(nil),       // 2: PostNewGLAcctJrnlEntryRs
	(*GLAccountEntry)(nil),                 // 3: GLAccountEntry
	(*NewGLAcctJournalEntry_AcctInfo)(nil), // 4: NewGLAcctJournalEntry.AcctInfo
	nil,                                    // 5: NewGLAcctJournalEntry.AdditionalInfoEntry
	nil,                                    // 6: PostNewGLAcctJrnlEntryRq.MetaEntry
}
var file_gl_account_journal_proto_depIdxs = []int32{
	4, // 0: NewGLAcctJournalEntry.debitInfo:type_name -> NewGLAcctJournalEntry.AcctInfo
	4, // 1: NewGLAcctJournalEntry.creditInfo:type_name -> NewGLAcctJournalEntry.AcctInfo
	5, // 2: NewGLAcctJournalEntry.additionalInfo:type_name -> NewGLAcctJournalEntry.AdditionalInfoEntry
	0, // 3: PostNewGLAcctJrnlEntryRq.entry:type_name -> NewGLAcctJournalEntry
	6, // 4: PostNewGLAcctJrnlEntryRq.meta:type_name -> PostNewGLAcctJrnlEntryRq.MetaEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gl_account_journal_proto_init() }
func file_gl_account_journal_proto_init() {
	if File_gl_account_journal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gl_account_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGLAcctJournalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostNewGLAcctJrnlEntryRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_journal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostNewGLAcctJrnlEntryRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_journal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GLAccountEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_account_journal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGLAcctJournalEntry_AcctInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gl_account_journal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gl_account_journal_proto_goTypes,
		DependencyIndexes: file_gl_account_journal_proto_depIdxs,
		MessageInfos:      file_gl_account_journal_proto_msgTypes,
	}.Build()
	File_gl_account_journal_proto = out.File
	file_gl_account_journal_proto_rawDesc = nil
	file_gl_account_journal_proto_goTypes = nil
	file_gl_account_journal_proto_depIdxs = nil
}
