// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: journal.proto

package glaccount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcctInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcctId      string  `protobuf:"bytes,1,opt,name=acctId,proto3" json:"acctId,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount      float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AcctInfo) Reset() {
	*x = AcctInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctInfo) ProtoMessage() {}

func (x *AcctInfo) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctInfo.ProtoReflect.Descriptor instead.
func (*AcctInfo) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{0}
}

func (x *AcctInfo) GetAcctId() string {
	if x != nil {
		return x.AcctId
	}
	return ""
}

func (x *AcctInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AcctInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type NewJournalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string            `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	ExternalRef   string            `protobuf:"bytes,2,opt,name=externalRef,proto3" json:"externalRef,omitempty"`
	EntryDate     string            `protobuf:"bytes,3,opt,name=entryDate,proto3" json:"entryDate,omitempty"`
	DebitInfo     *AcctInfo         `protobuf:"bytes,4,opt,name=debitInfo,proto3" json:"debitInfo,omitempty"`
	CreditInfo    *AcctInfo         `protobuf:"bytes,5,opt,name=creditInfo,proto3" json:"creditInfo,omitempty"`
	Tags          map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NewJournalEntry) Reset() {
	*x = NewJournalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewJournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewJournalEntry) ProtoMessage() {}

func (x *NewJournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewJournalEntry.ProtoReflect.Descriptor instead.
func (*NewJournalEntry) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{1}
}

func (x *NewJournalEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *NewJournalEntry) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *NewJournalEntry) GetEntryDate() string {
	if x != nil {
		return x.EntryDate
	}
	return ""
}

func (x *NewJournalEntry) GetDebitInfo() *AcctInfo {
	if x != nil {
		return x.DebitInfo
	}
	return nil
}

func (x *NewJournalEntry) GetCreditInfo() *AcctInfo {
	if x != nil {
		return x.CreditInfo
	}
	return nil
}

func (x *NewJournalEntry) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostNewJournalEntryRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *NewJournalEntry  `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Tags  map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PostNewJournalEntryRq) Reset() {
	*x = PostNewJournalEntryRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostNewJournalEntryRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewJournalEntryRq) ProtoMessage() {}

func (x *PostNewJournalEntryRq) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewJournalEntryRq.ProtoReflect.Descriptor instead.
func (*PostNewJournalEntryRq) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{2}
}

func (x *PostNewJournalEntryRq) GetEntry() *NewJournalEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *PostNewJournalEntryRq) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type PostNewJournalEntryRs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PostNewJournalEntryRs) Reset() {
	*x = PostNewJournalEntryRs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostNewJournalEntryRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostNewJournalEntryRs) ProtoMessage() {}

func (x *PostNewJournalEntryRs) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostNewJournalEntryRs.ProtoReflect.Descriptor instead.
func (*PostNewJournalEntryRs) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{3}
}

func (x *PostNewJournalEntryRs) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PostNewJournalEntryRs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JournalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalRef string `protobuf:"bytes,2,opt,name=externalRef,proto3" json:"externalRef,omitempty"`
	ReversalId  string `protobuf:"bytes,3,opt,name=reversalId,proto3" json:"reversalId,omitempty"`
	EntryDate   string `protobuf:"bytes,4,opt,name=entryDate,proto3" json:"entryDate,omitempty"`
	GlAccountId string `protobuf:"bytes,5,opt,name=glAccountId,proto3" json:"glAccountId,omitempty"`
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{4}
}

func (x *JournalEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JournalEntry) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *JournalEntry) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

func (x *JournalEntry) GetEntryDate() string {
	if x != nil {
		return x.EntryDate
	}
	return ""
}

func (x *JournalEntry) GetGlAccountId() string {
	if x != nil {
		return x.GlAccountId
	}
	return ""
}

var File_journal_proto protoreflect.FileDescriptor

var file_journal_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x5c, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x63, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb4, 0x02,
	0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x64, 0x65, 0x62, 0x69, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x64, 0x65, 0x62, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x29, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x4e, 0x65, 0x77, 0x4a,
	0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x54, 0x61, 0x67, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x54,
	0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xae, 0x01, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x77,
	0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x71, 0x12, 0x26,
	0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x77, 0x4a, 0x6f,
	0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x71, 0x2e, 0x54, 0x61, 0x67,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x37, 0x0a, 0x09,
	0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65, 0x77,
	0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x75, 0x72, 0x6e,
	0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x6c, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x6c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x27, 0x5a, 0x25, 0x61, 0x63, 0x68,
	0x75, 0x61, 0x6c, 0x61, 0x2e, 0x69, 0x6e, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x67,
	0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x67, 0x6c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_journal_proto_rawDescOnce sync.Once
	file_journal_proto_rawDescData = file_journal_proto_rawDesc
)

func file_journal_proto_rawDescGZIP() []byte {
	file_journal_proto_rawDescOnce.Do(func() {
		file_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_journal_proto_rawDescData)
	})
	return file_journal_proto_rawDescData
}

var file_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_journal_proto_goTypes = []interface{}{
	(*AcctInfo)(nil),              // 0: AcctInfo
	(*NewJournalEntry)(nil),       // 1: NewJournalEntry
	(*PostNewJournalEntryRq)(nil), // 2: PostNewJournalEntryRq
	(*PostNewJournalEntryRs)(nil), // 3: PostNewJournalEntryRs
	(*JournalEntry)(nil),          // 4: JournalEntry
	nil,                           // 5: NewJournalEntry.TagsEntry
	nil,                           // 6: PostNewJournalEntryRq.TagsEntry
}
var file_journal_proto_depIdxs = []int32{
	0, // 0: NewJournalEntry.debitInfo:type_name -> AcctInfo
	0, // 1: NewJournalEntry.creditInfo:type_name -> AcctInfo
	5, // 2: NewJournalEntry.tags:type_name -> NewJournalEntry.TagsEntry
	1, // 3: PostNewJournalEntryRq.entry:type_name -> NewJournalEntry
	6, // 4: PostNewJournalEntryRq.tags:type_name -> PostNewJournalEntryRq.TagsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_journal_proto_init() }
func file_journal_proto_init() {
	if File_journal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewJournalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostNewJournalEntryRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostNewJournalEntryRs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_journal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_journal_proto_goTypes,
		DependencyIndexes: file_journal_proto_depIdxs,
		MessageInfos:      file_journal_proto_msgTypes,
	}.Build()
	File_journal_proto = out.File
	file_journal_proto_rawDesc = nil
	file_journal_proto_goTypes = nil
	file_journal_proto_depIdxs = nil
}
